#1 install snap toos,
# use yumdownloader and rpm install requires package,waiting for rhel official update repo;
- block:
  - name: Install requires package and remove on second installation
    shell: |
      yumdownloader snapd-selinux-2.47.1-1.el7.noarch
      rpm --force --nodeps -ivh snapd-selinux-2.47.1-1.el7.noarch.rpm
      test -e snapd-selinux-* && rm -rf snapd-selinux-*.rpm
      
  - name: Install snap tools
    yum: 
      name: snapd
      update_cache: yes      
  
  - name: enable and create link for snap
    shell: |
      systemctl enable --now snapd.socket
      ln -sf /var/lib/snapd/snap /snap
      
  - name: Install and upgrade core 
    shell: |
      snap install core 
      snap refresh core
      ln -sf /snap /data
    failed_when: false
  when: apache_certbot 
    
#2 install and configure Apache
- block:
  - name: install the IUS rpm from a remote repo
    yum:
      name: "{{apache_ius_url}}"
      state: present

  - name: Install httpd24u
    yum:
      name: [httpd24u,httpd24u-mod_ssl]
      skip_broken: yes
  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7') or ansible_distribution == 'Amazon'

- name: Install Apache
  yum:
    name: [httpd,mod_ssl]
  when: ansible_distribution_major_version == '8'

- name: Create default Directory
  file:
    path: /data/config/apache
    state: directory
    
- name: Create Vhost Configure Directory
  file:
    path: /etc/httpd/vhost
    state: directory
  
- name: Set apache server or apache reverse proxy
  template:
    src: vhost.jinja2
    dest: /etc/httpd/conf.d/vhost.conf

- name: Create a Apache Log symbolic link
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /var/log/httpd,dest: /data/logs/apache}  # Apache 日志软连接
    - {src: /etc/httpd/vhost,dest: /data/config/apache/vhost} # Apache 虚拟主机配置软连接
    - {src: /etc/httpd/conf.modules.d,dest: /data/config/apache/conf.modules.d} # Apache 模块配置软连接
    - {src: /etc/httpd/conf.d/vhost.conf,dest: /etc/httpd/vhost/vhost.conf}  # Apache vhost 配置软链接

- name: Change Directory Owner
  file:
    path: /data/{{item}}
    state: directory
    owner: apache
    group: apache
  with_items:
    - wwwroot
    - cert 

- name: Link Apache service
  file:
    src: /usr/lib/systemd/system/httpd.service
    dest: /usr/lib/systemd/system/apache.service
    state: link

- name: set auto access index page
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "    DirectoryIndex index.html"
    line: "    DirectoryIndex {{apache_default_index}}"
    backrefs: yes
    
- name: Using 127.0.1.1 for ServerName
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "#ServerName localhost:80"
    line: "ServerName localhost:80"
      
- name: Start Apache
  service:
    name: httpd
    state: restarted
    enabled: yes

- name: Check Apache Version
  shell: sudo sh -c 'echo "httpd  $( httpd -v | sed -n 1p)" 1>> /data/logs/install_version.txt'
